### ISSUE TITLE
Is there a test set for GPT-4 (Jun 2023)?

### ISSUE THREAD

**Issue by Hwwg** [q-rz/enamel#2]
I didn’t see GPT-4 (Jun) 2023) under https://huggingface.co/datasets/q-rz/enamel/tree/main/samples~

**Comment by q-rz** [comment]
Sorry for the confusion. The samples of some models (including GPT-4) are already provided by EvalPlus at https://github.com/evalplus/evalplus/releases/tag/v0.1.0 , so we re-used them. Our `demo.py` supports EvalPlus' `.zip` files. You can download their `.zip` files into our `samples/` folder and run our `demo.py`. See detailed instructions at https://github.com/q-rz/enamel?tab=readme-ov-file#evaluating-zipped-code-samples-provided-by-evalplus

**Comment by Hwwg** [comment]
<img width="417" alt="image" src="https://github.com/user-attachments/assets/df0d7211-08d8-4981-95df-b897d450eded">
<img width="421" alt="image" src="https://github.com/user-attachments/assets/30969393-47b2-437c-bc55-04111c986fcb">
Thank you so much, but I still have some questions about the evaluation process. Why can case2 pass but case1 cannot? In the process of judging pass@1, does enamel only judge whether the test case can generate results normally? Will timeout factors be taken into account?

**Comment by Hwwg** [comment]
Thank you so much～
